# Generated by Django 5.2.12 on 2026-04-25 22:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_branch_historicaluserprofile_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCostCenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(db_index=True, help_text='رقم تعريف فريد لمركز التكلفة', max_length=20, verbose_name='رقم المركز')),
                ('name', models.CharField(help_text='الاسم الكامل لمركز التكلفة', max_length=200, verbose_name='اسم المركز')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='الميزانية السنوية المخصصة', max_digits=15, verbose_name='الميزانية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='الفرع')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'السجل التاريخي',
                'verbose_name_plural': 'historical مراكز التكلفة',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(help_text='رقم تعريف فريد لمركز التكلفة', max_length=20, unique=True, verbose_name='رقم المركز')),
                ('name', models.CharField(help_text='الاسم الكامل لمركز التكلفة', max_length=200, verbose_name='اسم المركز')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='الميزانية السنوية المخصصة', max_digits=15, verbose_name='الميزانية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'db_table': 'cost_centers',
                'ordering': ['code', 'name'],
                'indexes': [models.Index(fields=['branch', 'code'], name='cost_center_branch__d45d3e_idx'), models.Index(fields=['is_active'], name='cost_center_is_acti_5a8c08_idx')],
            },
        ),
    ]
