# Generated by Django 5.2.12 on 2026-05-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_systemauditlog'),
        ('employees', '0024_alter_employeeledger_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الجهاز')),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco / ZK')], default='zkteco', max_length=20, verbose_name='نوع الجهاز')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='منفذ الاتصال')),
                ('comm_key', models.PositiveIntegerField(default=0, help_text='عادة 0 — راجع إعدادات الجهاز', verbose_name='كلمة اتصال الجهاز (Comm Key)')),
                ('serial_number', models.CharField(blank=True, max_length=64, verbose_name='الرقم التسلسلي')),
                ('firmware_version', models.CharField(blank=True, max_length=64, verbose_name='إصدار البرنامج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('connection_status', models.CharField(choices=[('unknown', 'غير معروف'), ('online', 'متصل'), ('offline', 'غير متصل'), ('error', 'خطأ')], default='unknown', max_length=20, verbose_name='حالة الاتصال')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_ping_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فحص اتصال')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('device_user_id', models.PositiveIntegerField(db_index=True, verbose_name='رقم المستخدم على الجهاز')),
                ('punched_at', models.DateTimeField(db_index=True, verbose_name='وقت البصمة')),
                ('punch_type', models.CharField(choices=[('in', 'دخول'), ('out', 'خروج'), ('break_out', 'خروج استراحة'), ('break_in', 'عودة استراحة'), ('unknown', 'غير محدد')], default='unknown', max_length=20, verbose_name='نوع الحركة')),
                ('verify_mode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طريقة التحقق')),
                ('device_record_uid', models.PositiveIntegerField(blank=True, help_text='لمنع التكرار عند المزامنة', null=True, verbose_name='معرف السجل على الجهاز')),
                ('raw_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حالة خام من الجهاز')),
                ('sync_batch', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='دفعة المزامنة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_punches', to='employees.employee', verbose_name='الموظف')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='attendance.biometricdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل بصمة',
                'verbose_name_plural': 'سجلات البصمة',
                'ordering': ['-punched_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBiometricEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('device_user_id', models.PositiveIntegerField(db_index=True, verbose_name='رقم المستخدم على الجهاز')),
                ('device_user_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم على الجهاز')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance.biometricdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrollments', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تسجيل بصمة موظف',
                'verbose_name_plural': 'تسجيلات البصمة',
            },
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['ip_address', 'port'], name='attendance__ip_addr_efc8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_49085f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['device', 'punched_at'], name='attendance__device__ba8fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['employee', 'punched_at'], name='attendance__employe_ab5738_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancepunch',
            constraint=models.UniqueConstraint(condition=models.Q(('device_record_uid__isnull', False)), fields=('device', 'device_record_uid'), name='uniq_device_attendance_uid'),
        ),
        migrations.AddConstraint(
            model_name='employeebiometricenrollment',
            constraint=models.UniqueConstraint(fields=('device', 'device_user_id'), name='uniq_device_user_per_device'),
        ),
        migrations.AddConstraint(
            model_name='employeebiometricenrollment',
            constraint=models.UniqueConstraint(fields=('device', 'employee'), name='uniq_employee_per_device'),
        ),
    ]
