# Generated by Django 5.2.12 on 2026-05-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='device_user_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم على الجهاز'),
        ),
        migrations.CreateModel(
            name='BiometricDeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('device_user_id', models.PositiveIntegerField(db_index=True, verbose_name='رقم المستخدم على الجهاز')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='الاسم على الجهاز')),
                ('card', models.CharField(blank=True, max_length=64, verbose_name='رقم البطاقة')),
                ('privilege', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='صلاحية الجهاز')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر سحب من الجهاز')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_users', to='attendance.biometricdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'مستخدم على جهاز البصمة',
                'verbose_name_plural': 'مستخدمو أجهزة البصمة',
                'ordering': ['device', 'device_user_id'],
                'constraints': [models.UniqueConstraint(fields=('device', 'device_user_id'), name='uniq_biometric_device_user')],
            },
        ),
    ]
