# Generated by Django 5.2.12 on 2026-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancepunch_device_user_name_biometricdeviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='verify_mode_label',
            field=models.CharField(blank=True, max_length=40, verbose_name='طريقة التحقق'),
        ),
        migrations.AlterField(
            model_name='attendancepunch',
            name='verify_mode',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طريقة التحقق (رمز ZK)'),
        ),
    ]
