# Generated by Django 5.2.12 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancepunch_verify_mode_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='punch_type_source',
            field=models.CharField(
                choices=[('device', 'من الجهاز (status)'), ('inferred', 'محسوب بالتسلسل')],
                db_index=True,
                default='device',
                max_length=20,
                verbose_name='مصدر تصنيف الحركة',
            ),
        ),
    ]
