"""Reset IDENTITY columns to MAX(col)+1.
Django 4.1+ on Postgres uses GENERATED BY DEFAULT AS IDENTITY (not nextval sequences).
"""
import os

import psycopg2
from psycopg2 import sql

DB_URL = os.environ['DATABASE_URL']
conn = psycopg2.connect(DB_URL)
conn.autocommit = True
cur = conn.cursor()

cur.execute(
    "SELECT table_name, column_name FROM information_schema.columns "
    "WHERE table_schema='public' AND is_identity='YES'"
)
cols = cur.fetchall()
for tbl, col in cols:
    cur.execute(
        sql.SQL('SELECT COALESCE(MAX({}), 0) FROM {}').format(
            sql.Identifier(col),
            sql.Identifier(tbl),
        )
    )
    mx = cur.fetchone()[0]
    nxt = mx + 1 if mx > 0 else 1
    cur.execute(
        sql.SQL('ALTER TABLE {} ALTER COLUMN {} RESTART WITH %s').format(
            sql.Identifier(tbl),
            sql.Identifier(col),
        ),
        (nxt,),
    )
    print(f'  {tbl}.{col}: MAX={mx} -> RESTART WITH {nxt}')
print(f'\nReset {len(cols)} identity columns.')
