# Generated by Django 5.2.12 on 2026-04-25 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='رمز الصلاحية')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصلاحية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('module', models.CharField(choices=[('employees', 'الموظفين'), ('departments', 'الأقسام'), ('attendance', 'الحضور والغياب'), ('leaves', 'الإجازات'), ('payroll', 'الرواتب'), ('users', 'المستخدمين'), ('reports', 'التقارير'), ('settings', 'الإعدادات')], max_length=100, verbose_name='الوحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'إعداد نظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('role_type', models.CharField(choices=[('admin', 'مدير النظام'), ('hr_manager', 'مدير موارد بشرية'), ('employee', 'موظف'), ('manager', 'مدير قسم')], default='employee', max_length=20, verbose_name='نوع الدور')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_system_role', models.BooleanField(default=False, help_text='الأدوار الأساسية لا يمكن حذفها', verbose_name='دور نظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='المنصب')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('is_protected', models.BooleanField(default=False, help_text='المستخدمين المحميين لا يمكن حذفهم أو تعديلهم', verbose_name='محمي')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.role', verbose_name='الدور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
