# Generated by Django 5.2.12 on 2026-04-25 20:28

import django.db.models.deletion
from django.db import migrations, models


def migrate_modules_data(apps, schema_editor):
    """نقل البيانات من module (CharField) إلى AppModule (ForeignKey)"""
    Permission = apps.get_model('core', 'Permission')
    AppModule = apps.get_model('core', 'AppModule')
    
    # تعريف الوحدات الموجودة حالياً
    modules_config = {
        'employees': {'name': 'الموظفين', 'name_en': 'Employees', 'icon': 'users', 'order': 1},
        'departments': {'name': 'الأقسام', 'name_en': 'Departments', 'icon': 'building', 'order': 2},
        'attendance': {'name': 'الحضور والغياب', 'name_en': 'Attendance', 'icon': 'calendar-check', 'order': 3},
        'leaves': {'name': 'الإجازات', 'name_en': 'Leaves', 'icon': 'calendar-x', 'order': 4},
        'payroll': {'name': 'الرواتب', 'name_en': 'Payroll', 'icon': 'dollar-sign', 'order': 5},
        'users': {'name': 'المستخدمين', 'name_en': 'Users', 'icon': 'user-cog', 'order': 6},
        'reports': {'name': 'التقارير', 'name_en': 'Reports', 'icon': 'bar-chart', 'order': 7},
        'settings': {'name': 'الإعدادات', 'name_en': 'Settings', 'icon': 'settings', 'order': 8},
    }
    
    # استخدام SQL مباشرة للحصول على القيم
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute('SELECT DISTINCT module_old FROM core_permission WHERE module_old IS NOT NULL')
        existing_module_codes = [row[0] for row in cursor.fetchall()]
    
    module_mapping = {}
    
    for module_code in existing_module_codes:
        if not module_code:
            continue
            
        config = modules_config.get(module_code, {
            'name': module_code,
            'name_en': module_code.replace('_', ' ').title(),
            'icon': 'folder',
            'order': 999
        })
        
        app_module, created = AppModule.objects.get_or_create(
            code=module_code,
            defaults={
                'name': config['name'],
                'name_en': config['name_en'],
                'icon': config['icon'],
                'order': config['order'],
                'is_active': True,
            }
        )
        module_mapping[module_code] = app_module
    
    # ربط الصلاحيات بالوحدات الجديدة باستخدام SQL
    with connection.cursor() as cursor:
        for module_code, app_module in module_mapping.items():
            cursor.execute(
                'UPDATE core_permission SET module_new_id = %s WHERE module_old = %s',
                [app_module.id, module_code]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_permission_deleted_at_permission_is_deleted_and_more'),
    ]

    operations = [
        # 1️⃣ إنشاء جدول AppModule
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(help_text='اسم الـ app في Django', max_length=100, unique=True, verbose_name='رمز الوحدة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوحدة بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم الوحدة بالإنجليزية')),
                ('icon', models.CharField(blank=True, help_text='اسم أيقونة Lucide', max_length=50, verbose_name='أيقونة')),
                ('order', models.IntegerField(default=0, help_text='ترتيب العرض في القوائم', verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['order', 'name'],
            },
        ),
        
        # 2️⃣ إعادة تسمية الحقل القديم
        migrations.RenameField(
            model_name='permission',
            old_name='module',
            new_name='module_old',
        ),
        
        # 3️⃣ إضافة حقل جديد (ForeignKey)
        migrations.AddField(
            model_name='permission',
            name='module_new',
            field=models.ForeignKey(
                null=True,  # مؤقت للسماح بالبيانات الفارغة
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permissions',
                to='core.appmodule',
                verbose_name='الوحدة'
            ),
        ),
        
        # 4️⃣ نقل البيانات
        migrations.RunPython(migrate_modules_data, reverse_code=migrations.RunPython.noop),
        
        # 5️⃣ حذف الحقل القديم
        migrations.RemoveField(
            model_name='permission',
            name='module_old',
        ),
        
        # 6️⃣ إعادة تسمية الحقل الجديد
        migrations.RenameField(
            model_name='permission',
            old_name='module_new',
            new_name='module',
        ),
        
        # 7️⃣ جعل الحقل إلزامي
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='permissions',
                to='core.appmodule',
                verbose_name='الوحدة'
            ),
        ),
        
        # 8️⃣ تحديث ordering
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module__order', 'module__name', 'name'], 'verbose_name': 'صلاحية', 'verbose_name_plural': 'الصلاحيات'},
        ),
    ]
