# Generated by Django 5.2.12 on 2026-04-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appmodule_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='module',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='AppModule',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
