# Generated by Django 5.2.12 on 2026-04-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_permission_module_remove_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('hr_manager', 'مدير موارد بشرية'), ('manager', 'مدير قسم'), ('specialist', 'أخصائي'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('hr_manager', 'مدير موارد بشرية'), ('manager', 'مدير قسم'), ('specialist', 'أخصائي'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
    ]
