# Generated by Django 5.2.12 on 2026-04-25 22:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicalrole_role_type_alter_role_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('code', models.CharField(help_text='رمز مختصر للفرع', max_length=20, unique=True, verbose_name='رمز الفرع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company', verbose_name='الشركة')),
                ('manager', models.ForeignKey(blank=True, help_text='المدير المسؤول عن هذا الفرع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='الفرع الذي ينتمي له المستخدم', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, help_text='الفروع التي يمكن للأخصائي الوصول إليها (يحددها مدير الموارد البشرية)', related_name='assigned_specialists', to='core.branch', verbose_name='الفروع المكلف بها'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع الذي ينتمي له المستخدم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.CreateModel(
            name='HistoricalBranch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('code', models.CharField(db_index=True, help_text='رمز مختصر للفرع', max_length=20, verbose_name='رمز الفرع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company', verbose_name='الشركة')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, help_text='المدير المسؤول عن هذا الفرع', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع')),
            ],
            options={
                'verbose_name': 'historical فرع',
                'verbose_name_plural': 'historical الفروع',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
