# Generated by Django 5.2.12 on 2026-04-25 22:58

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_departments(apps, schema_editor):
    """Clear empty department strings before converting to ForeignKey"""
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(department='').update(department=None)
    
    # Also handle HistoricalUserProfile if it exists
    try:
        HistoricalUserProfile = apps.get_model('core', 'HistoricalUserProfile')
        HistoricalUserProfile.objects.filter(department='').update(department=None)
    except LookupError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_historicaluserprofile_branch_and_more'),
        ('departments', '0001_initial'),
    ]

    operations = [
        # First, convert department field to nullable CharField
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم'),
        ),
        # Clear empty strings
        migrations.RunPython(clear_empty_departments, migrations.RunPython.noop),
        # Now convert to ForeignKey
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='القسم الذي ينتمي له الموظف', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='القسم الذي ينتمي له الموظف', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='القسم'),
        ),
    ]
