# Generated by Django 5.2.12 on 2026-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_insurance_insuranceclass_nationality_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='user_number',
            field=models.CharField(blank=True, db_index=True, help_text='رقم المستخدم للدخول', max_length=20, null=True, verbose_name='رقم المستخدم'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_number',
            field=models.CharField(blank=True, help_text='رقم المستخدم للدخول', max_length=20, null=True, unique=True, verbose_name='رقم المستخدم'),
        ),
    ]
