# Generated by Django 5.2.12 on 2026-04-28 11:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historicaluserprofile_user_number_and_more'),
        ('employees', '0004_employeestatement_email_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPendingAction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('action_type', models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط')], db_index=True, max_length=20, verbose_name='نوع العملية')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات العملية')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='مرفق')),
                ('requested_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('execution_error', models.TextField(blank=True, verbose_name='خطأ التنفيذ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, help_text='يُستخدم لتوجيه الطلب لمدير الفرع المسؤول', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='الموظف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
            ],
            options={
                'verbose_name': 'historical طلب عملية معلّق',
                'verbose_name_plural': 'historical طلبات العمليات المعلّقة',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('action_type', models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط')], db_index=True, max_length=20, verbose_name='نوع العملية')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات العملية')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pending_actions/', verbose_name='مرفق')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('execution_error', models.TextField(blank=True, verbose_name='خطأ التنفيذ')),
                ('branch', models.ForeignKey(blank=True, help_text='يُستخدم لتوجيه الطلب لمدير الفرع المسؤول', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='core.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='employees.employee', verbose_name='الموظف')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pending_actions', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pending_actions', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
            ],
            options={
                'verbose_name': 'طلب عملية معلّق',
                'verbose_name_plural': 'طلبات العمليات المعلّقة',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='core_pendin_status_a7c16f_idx'), models.Index(fields=['branch', 'status'], name='core_pendin_branch__8d8c42_idx')],
            },
        ),
    ]
