# Generated by Django 5.2.12 on 2026-04-28 12:43

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalpendingaction_pendingaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='pending_actions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مرفق'),
        ),
    ]
