# Generated by Django 5.2.12 on 2026-04-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historicalpendingaction_attachment_and_more'),
        ('employees', '0006_alter_employee_insurance_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.RemoveField(
            model_name='historicalinsurance',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinsuranceclass',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnationality',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofession',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsponsorship',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='InsuranceClass',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.DeleteModel(
            name='HistoricalInsurance',
        ),
        migrations.DeleteModel(
            name='HistoricalInsuranceClass',
        ),
        migrations.DeleteModel(
            name='HistoricalNationality',
        ),
        migrations.DeleteModel(
            name='HistoricalProfession',
        ),
        migrations.DeleteModel(
            name='HistoricalSponsorship',
        ),
            ],
            database_operations=[],
        ),
    ]
