# Generated by Django 5.2.12 on 2026-05-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_clear_legacy_file_paths'),
        ('employees', '0007_employee_passport_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='الرابط')),
                ('icon', models.CharField(default='bell', max_length=40, verbose_name='الأيقونة')),
                ('color', models.CharField(choices=[('primary', 'أزرق'), ('emerald', 'أخضر'), ('amber', 'برتقالي'), ('red', 'أحمر'), ('indigo', 'بنفسجي'), ('slate', 'رمادي')], default='primary', max_length=12, verbose_name='اللون')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='موظف الموارد المُعيَّن'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='branch_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مدير الفرع'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='branch_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة مدير الفرع'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='branch_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='موافقة مدير الفرع'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='gm_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المدير العام'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='gm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة المدير العام'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='gm_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='موافقة المدير العام'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='officer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات موظف الموارد'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة موظف الموارد'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='resubmit_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد مرات إعادة الإرسال'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='return_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإرجاع'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرجاع'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='returned_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مَن أرجعه'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='returned_from_stage',
            field=models.CharField(blank=True, choices=[('branch', 'مدير الفرع'), ('gm', 'المدير العام'), ('officer', 'موظف الموارد')], default='', max_length=10, verbose_name='المرحلة التي رُجِع منها'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pending_actions', to=settings.AUTH_USER_MODEL, verbose_name='موظف الموارد المُعيَّن'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='branch_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مدير الفرع'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='branch_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة مدير الفرع'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='branch_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_reviewed_actions', to=settings.AUTH_USER_MODEL, verbose_name='موافقة مدير الفرع'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='gm_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المدير العام'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='gm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة المدير العام'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='gm_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_reviewed_actions', to=settings.AUTH_USER_MODEL, verbose_name='موافقة المدير العام'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='officer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات موظف الموارد'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة موظف الموارد'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='resubmit_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد مرات إعادة الإرسال'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='return_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإرجاع'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرجاع'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_pending_actions', to=settings.AUTH_USER_MODEL, verbose_name='مَن أرجعه'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='returned_from_stage',
            field=models.CharField(blank=True, choices=[('branch', 'مدير الفرع'), ('gm', 'المدير العام'), ('officer', 'موظف الموارد')], default='', max_length=10, verbose_name='المرحلة التي رُجِع منها'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='(قديم) ملاحظات المراجعة'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='(قديم) تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='(قديم) راجعها'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='status',
            field=models.CharField(choices=[('pending_branch', 'بانتظار مدير الفرع'), ('pending_gm', 'بانتظار المدير العام'), ('pending_officer', 'بانتظار موظف الموارد'), ('approved', 'مُنفَّذ'), ('returned', 'مُرتجَع للتعديل')], db_index=True, default='pending_branch', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('hr_manager', 'مدير موارد بشرية'), ('hr_officer', 'موظف موارد'), ('manager', 'مدير قسم'), ('specialist', 'أخصائي'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='(قديم) ملاحظات المراجعة'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='(قديم) تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pending_actions', to=settings.AUTH_USER_MODEL, verbose_name='(قديم) راجعها'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='status',
            field=models.CharField(choices=[('pending_branch', 'بانتظار مدير الفرع'), ('pending_gm', 'بانتظار المدير العام'), ('pending_officer', 'بانتظار موظف الموارد'), ('approved', 'مُنفَّذ'), ('returned', 'مُرتجَع للتعديل')], db_index=True, default='pending_branch', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('hr_manager', 'مدير موارد بشرية'), ('hr_officer', 'موظف موارد'), ('manager', 'مدير قسم'), ('specialist', 'أخصائي'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AddIndex(
            model_name='pendingaction',
            index=models.Index(fields=['assigned_officer', 'status'], name='core_pendin_assigne_345b3d_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.pendingaction', verbose_name='الطلب المرتبط'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx'),
        ),
    ]
