# Generated by Django 5.2.12 on 2026-05-06 11:14

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ensure_hr_officer_role_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='logo',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size], verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size], verbose_name='الصورة الشخصية'),
        ),
    ]
