# Generated by Django 5.2.12 on 2026-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appmodule_historicalappmodule_historicalpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='denied_permissions',
            field=models.ManyToManyField(blank=True, help_text='صلاحيات تُسحب من هذا المستخدم حتى لو كانت في الدور', related_name='denied_users', to='core.permission', verbose_name='صلاحيات مرفوضة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, help_text='صلاحيات تُمنح لهذا المستخدم تحديداً بالإضافة إلى صلاحيات الدور', related_name='extra_users', to='core.permission', verbose_name='صلاحيات إضافية'),
        ),
    ]
