# Generated by Django 5.2.12 on 2026-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_historicalpendingaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='action_type',
            field=models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط'), ('custody_receive', 'استلام عهدة'), ('custody_clear', 'تصفية عهدة'), ('job_offer', 'عرض وظيفي'), ('business_trip', 'رحلة عمل'), ('loan_request', 'تقديم سلفة'), ('absence', 'تسجيل غياب'), ('contract_end', 'انتهاء عقد')], db_index=True, max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط'), ('custody_receive', 'استلام عهدة'), ('custody_clear', 'تصفية عهدة'), ('job_offer', 'عرض وظيفي'), ('business_trip', 'رحلة عمل'), ('loan_request', 'تقديم سلفة'), ('absence', 'تسجيل غياب'), ('contract_end', 'انتهاء عقد')], db_index=True, max_length=20, verbose_name='نوع العملية'),
        ),
    ]
