# Generated by Django 5.2.12 on 2026-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_contract_end_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التنفيذ')),
                ('trigger', models.CharField(choices=[('manual', 'يدوي'), ('cron', 'مجدول (Cron)')], db_index=True, default='manual', max_length=16, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('success', 'نجاح كامل'), ('partial', 'نجاح جزئي (محلي — فشل الرفع لـ R2)'), ('failed', 'فشل')], db_index=True, max_length=16, verbose_name='الحالة')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('r2_key', models.CharField(blank=True, max_length=512, verbose_name='مفتاح R2')),
                ('dump_error', models.TextField(blank=True, verbose_name='خطأ النسخ')),
                ('r2_error', models.TextField(blank=True, verbose_name='خطأ رفع R2')),
            ],
            options={
                'verbose_name': 'سجل نسخ احتياطي',
                'verbose_name_plural': 'سجلات النسخ الاحتياطي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='action_type',
            field=models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط'), ('custody_receive', 'استلام عهدة'), ('custody_clear', 'تصفية عهدة'), ('job_offer', 'عرض وظيفي'), ('business_trip', 'رحلة عمل'), ('loan_request', 'تقديم سلفة'), ('absence', 'تسجيل غياب'), ('contract_end', 'انتهاء عقد'), ('end_of_service', 'تصفية نهاية خدمة / استقالة')], db_index=True, max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط'), ('custody_receive', 'استلام عهدة'), ('custody_clear', 'تصفية عهدة'), ('job_offer', 'عرض وظيفي'), ('business_trip', 'رحلة عمل'), ('loan_request', 'تقديم سلفة'), ('absence', 'تسجيل غياب'), ('contract_end', 'انتهاء عقد'), ('end_of_service', 'تصفية نهاية خدمة / استقالة')], db_index=True, max_length=20, verbose_name='نوع العملية'),
        ),
    ]
