# Generated by Django 5.2.12 on 2026-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_database_backup_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackuplog',
            name='trigger',
            field=models.CharField(choices=[('manual', 'يدوي'), ('cron', 'مجدول (Cron)'), ('migrate', 'قبل المهاجرات')], db_index=True, default='manual', max_length=16, verbose_name='المصدر'),
        ),
    ]
