# Generated by Django 5.2.12 on 2026-06-04 02:22

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_employee_tab_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingaction',
            new_name='core_pendin_adminis_27f153_idx',
            old_name='core_pendin_adminis_d3e0f8_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='logo',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='pending_actions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, help_text='فروع يصل إليها المستخدم (إضافةً لتعيين مدير الإدارة من التهيئة)', related_name='assigned_specialists', to='core.branch', verbose_name='الفروع المعينة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png, webp, gif'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='الصورة الشخصية'),
        ),
    ]
