# Generated by Django 5.2.12 on 2026-06-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_job_offer_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='action_type',
            field=models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط'), ('custody_receive', 'استلام عهدة'), ('custody_clear', 'تصفية عهدة'), ('business_trip', 'رحلة عمل'), ('loan_request', 'تقديم سلفة'), ('absence', 'تسجيل غياب'), ('cash_shortage', 'عجز كاشير'), ('contract_end', 'انتهاء عقد'), ('end_of_service', 'تصفية نهاية خدمة / استقالة')], db_index=True, max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'ADMIN — مدير النظام (صلاحيات كاملة)'), ('hr_manager', 'HR_MANAGER — مدير الموارد البشرية (المدير العام)'), ('hr_officer', 'HR_OFFICER — منفّذ عمليات الموارد البشرية'), ('admin_manager', 'ADMIN_MANAGER — مدير الإدارة (موافقة أولى)'), ('manager', 'BRANCH_MANAGER — مدير الفرع (موافقة أولى)'), ('branch_accountant', 'BRANCH_ACCOUNTANT — محاسب الفرع'), ('specialist', 'DATA_SPECIALIST — أخصائي إدخال البيانات'), ('employee', 'EMPLOYEE — موظف (صلاحيات ذاتية)')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('leave', 'تقديم إجازة'), ('transfer', 'نقل'), ('salary_adjust', 'تعديل راتب'), ('terminate', 'إنهاء خدمة'), ('reactivate', 'إعادة تنشيط'), ('custody_receive', 'استلام عهدة'), ('custody_clear', 'تصفية عهدة'), ('business_trip', 'رحلة عمل'), ('loan_request', 'تقديم سلفة'), ('absence', 'تسجيل غياب'), ('cash_shortage', 'عجز كاشير'), ('contract_end', 'انتهاء عقد'), ('end_of_service', 'تصفية نهاية خدمة / استقالة')], db_index=True, max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'ADMIN — مدير النظام (صلاحيات كاملة)'), ('hr_manager', 'HR_MANAGER — مدير الموارد البشرية (المدير العام)'), ('hr_officer', 'HR_OFFICER — منفّذ عمليات الموارد البشرية'), ('admin_manager', 'ADMIN_MANAGER — مدير الإدارة (موافقة أولى)'), ('manager', 'BRANCH_MANAGER — مدير الفرع (موافقة أولى)'), ('branch_accountant', 'BRANCH_ACCOUNTANT — محاسب الفرع'), ('specialist', 'DATA_SPECIALIST — أخصائي إدخال البيانات'), ('employee', 'EMPLOYEE — موظف (صلاحيات ذاتية)')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
    ]
