# Generated by Django 5.2.12 on 2026-06-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cash_shortage_feature'),
        ('employees', '0038_cash_shortage_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=24, verbose_name='رقم الجوال')),
                ('event_type', models.CharField(db_index=True, max_length=80, verbose_name='نوع الحدث')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('status', models.CharField(choices=[('sent', 'مُرسَل'), ('failed', 'فشل'), ('skipped', 'تخطّي')], db_index=True, default='skipped', max_length=12, verbose_name='الحالة')),
                ('response', models.TextField(blank=True, verbose_name='استجابة Evolution API')),
                ('error', models.TextField(blank=True, verbose_name='خطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإرسال')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='employees.employee', verbose_name='الموظف')),
                ('related_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.pendingaction', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'سجل WhatsApp',
                'verbose_name_plural': 'سجلات WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_whatsa_status_11c149_idx'), models.Index(fields=['event_type', '-created_at'], name='core_whatsa_event_t_dff771_idx')],
            },
        ),
    ]
