# Generated by Django 5.2.12 on 2026-06-22 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_settlement_execute_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_received', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستلم'),
        ),
        migrations.AlterField(
            model_name='historicalpermission',
            name='operation',
            field=models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('edit', 'تعديل'), ('delete', 'حذف'), ('approve_branch', 'موافقة الفرع'), ('approve_admin', 'موافقة الإدارة'), ('approve_gm', 'موافقة المدير العام'), ('approve_officer', 'تنفيذ موظف الموارد'), ('return', 'إرجاع'), ('resubmit', 'إعادة إرسال'), ('execute', 'تنفيذ')], max_length=32, verbose_name='العملية'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='operation',
            field=models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('edit', 'تعديل'), ('delete', 'حذف'), ('approve_branch', 'موافقة الفرع'), ('approve_admin', 'موافقة الإدارة'), ('approve_gm', 'موافقة المدير العام'), ('approve_officer', 'تنفيذ موظف الموارد'), ('return', 'إرجاع'), ('resubmit', 'إعادة إرسال'), ('execute', 'تنفيذ')], max_length=32, verbose_name='العملية'),
        ),
    ]
