# Generated by Django 5.2.12 on 2026-06-22 18:34

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_workflow_whatsapp_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='logo',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'xlsx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, png, xlsx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='pending_actions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'xlsx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, png, xlsx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='الصورة الشخصية'),
        ),
    ]
