# Generated by Django 5.2.12 on 2026-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_employee_leave_manage_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'ADMIN — مدير النظام (صلاحيات كاملة)'), ('hr_manager', 'HR_MANAGER — مدير الموارد البشرية (المدير العام)'), ('hr_officer', 'HR_OFFICER — منفّذ عمليات الموارد البشرية'), ('admin_manager', 'ADMIN_MANAGER — مدير الإدارة (موافقة أولى)'), ('manager', 'BRANCH_MANAGER — مدير الفرع (موافقة أولى)'), ('branch_accountant', 'BRANCH_ACCOUNTANT — محاسب الفرع'), ('specialist', 'DATA_SPECIALIST — أخصائي إدخال البيانات'), ('employee', 'EMPLOYEE — موظف (صلاحيات ذاتية)'), ('maintenance_manager', 'MAINTENANCE_MANAGER — مدير الصيانة')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'ADMIN — مدير النظام (صلاحيات كاملة)'), ('hr_manager', 'HR_MANAGER — مدير الموارد البشرية (المدير العام)'), ('hr_officer', 'HR_OFFICER — منفّذ عمليات الموارد البشرية'), ('admin_manager', 'ADMIN_MANAGER — مدير الإدارة (موافقة أولى)'), ('manager', 'BRANCH_MANAGER — مدير الفرع (موافقة أولى)'), ('branch_accountant', 'BRANCH_ACCOUNTANT — محاسب الفرع'), ('specialist', 'DATA_SPECIALIST — أخصائي إدخال البيانات'), ('employee', 'EMPLOYEE — موظف (صلاحيات ذاتية)'), ('maintenance_manager', 'MAINTENANCE_MANAGER — مدير الصيانة')], default='employee', max_length=20, verbose_name='نوع الدور'),
        ),
    ]
