# Generated by Django 5.2.12 on 2026-06-09 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_core_pendin_adminis_d3e0f8_idx_core_pendin_adminis_27f153_idx_and_more'),
        ('payroll', '0006_payroll_run_kind_history'),
        ('setup', '0006_administration_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollrun',
            name='payroll_uniq_detailed_cash',
        ),
        migrations.RemoveConstraint(
            model_name='payrollrun',
            name='payroll_uniq_detailed_transfer',
        ),
        migrations.RenameIndex(
            model_name='payrollallocationline',
            new_name='payroll_pay_run_id_9e6e08_idx',
            old_name='payroll_alloc_run_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollallocationline',
            new_name='payroll_pay_run_id_ad86e4_idx',
            old_name='payroll_alloc_run_br_idx',
        ),
        migrations.AlterField(
            model_name='payrollallocationline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='payrollallocationline',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AlterField(
            model_name='payrollallocationline',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف'),
        ),
        migrations.AlterField(
            model_name='payrollallocationline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('run_kind', 'detailed')), fields=('company', 'period_year', 'period_month', 'salary_mode', 'sponsorship'), name='payroll_uniq_detailed_run'),
        ),
    ]
