# Generated by Django 5.2.12 on 2026-06-10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_core_pendin_adminis_d3e0f8_idx_core_pendin_adminis_27f153_idx_and_more'),
        ('payroll', '0007_restore_performance_indexes'),
        ('setup', '0006_administration_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='run_kind',
            field=models.CharField(
                choices=[
                    ('standard', 'مسير'),
                    ('consolidated', 'مسير موحّد'),
                    ('detailed', 'مسير تفصيلي'),
                ],
                db_index=True,
                default='standard',
                max_length=20,
                verbose_name='نوع المسير',
            ),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(('run_kind', 'consolidated')),
                fields=('company', 'period_year', 'period_month', 'salary_mode', 'sponsorship'),
                name='payroll_uniq_consolidated_run',
            ),
        ),
    ]
