# Generated by Django 5.2.12 on 2026-06-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payroll_consolidated_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayrollrun',
            name='run_kind',
            field=models.CharField(choices=[('standard', 'مسير'), ('consolidated', 'مسير موحّد'), ('detailed', 'مسير تفصيلي')], db_index=True, default='standard', max_length=20, verbose_name='نوع المسير'),
        ),
    ]
