# Generated by Django 5.2.12 on 2026-07-06 11:43

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0050_alter_historicalrole_role_type_alter_role_role_type'),
        ('employees', '0043_employee_search_payroll_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المهنة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المهنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مهنة صيانة',
                'verbose_name_plural': 'مهن الصيانة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_worker_profiles', to='employees.employee', verbose_name='موظف مرتبط')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='maintenance.maintenancetrade', verbose_name='المهنة')),
            ],
            options={
                'verbose_name': 'عامل صيانة',
                'verbose_name_plural': 'عمال الصيانة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('attachment', models.FileField(blank=True, upload_to='maintenance/requests/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='صيغة الصورة غير مدعومة. الصيغ المسموحة: jpg, jpeg, png'), apps.core.validators.validate_image_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مرفق')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإسناد'), ('assigned', 'عند العامل'), ('worker_reported', 'بانتظار إغلاق مدير الصيانة'), ('manager_closed', 'بانتظار تأكيد الفرع'), ('branch_confirmed', 'مكتمل'), ('returned', 'مرتجع')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإسناد')),
                ('worker_report_notes', models.TextField(blank=True, verbose_name='ملاحظات العامل')),
                ('worker_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بلاغ العامل')),
                ('worker_report_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='رمز بلاغ العامل')),
                ('manager_closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إغلاق المدير')),
                ('manager_notes', models.TextField(blank=True, verbose_name='ملاحظات مدير الصيانة')),
                ('branch_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تأكيد الفرع')),
                ('return_notes', models.TextField(blank=True, verbose_name='ملاحظات الإرجاع')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('resubmit_count', models.PositiveIntegerField(default=0, verbose_name='عدد إعادة التقديم')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='أُسند بواسطة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='core.branch', verbose_name='الفرع')),
                ('branch_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='أُكد بواسطة')),
                ('manager_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_closed', to=settings.AUTH_USER_MODEL, verbose_name='أُغلق بواسطة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='مُقدّم الطلب')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_returned', to=settings.AUTH_USER_MODEL, verbose_name='أُرجع بواسطة')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='maintenance.maintenanceworker', verbose_name='العامل المُسند')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceworker',
            index=models.Index(fields=['is_active', 'is_deleted'], name='maintenance_is_acti_42851a_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['branch', 'status'], name='maintenance_branch__03e840_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['requested_by', 'status'], name='maintenance_request_d2455b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['assigned_worker', 'status'], name='maintenance_assigne_a7e680_idx'),
        ),
    ]
