# Generated by Django 5.2.12 on 2026-07-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الأصل')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الأصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'أصل صيانة',
                'verbose_name_plural': 'أصول الصيانة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='maintenance.maintenanceasset', verbose_name='الأصل'),
        ),
    ]
