# Generated by Django 5.2.12 on 2026-04-27 10:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('statement_type', models.CharField(choices=[('statement', 'إفادة'), ('warning', 'إنذار'), ('final_warning', 'إنذار نهائي'), ('acknowledgment', 'إقرار'), ('other', 'أخرى')], default='statement', max_length=20, verbose_name='النوع')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('statement_date', models.DateField(verbose_name='التاريخ')),
                ('content', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('document', models.FileField(blank=True, null=True, upload_to='employees/statements/', verbose_name='مستند مرفق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_statements', to=settings.AUTH_USER_MODEL, verbose_name='أُضيفت بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_log', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إفادة / إنذار',
                'verbose_name_plural': 'الإفادات والإنذارات',
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeStatement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('statement_type', models.CharField(choices=[('statement', 'إفادة'), ('warning', 'إنذار'), ('final_warning', 'إنذار نهائي'), ('acknowledgment', 'إقرار'), ('other', 'أخرى')], default='statement', max_length=20, verbose_name='النوع')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('statement_date', models.DateField(verbose_name='التاريخ')),
                ('content', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('document', models.TextField(blank=True, max_length=100, null=True, verbose_name='مستند مرفق')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أُضيفت بواسطة')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='الموظف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical إفادة / إنذار',
                'verbose_name_plural': 'historical الإفادات والإنذارات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
