# Generated by Django 5.2.12 on 2026-04-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeleave_historicalemployeeleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatement',
            name='email_error',
            field=models.TextField(blank=True, verbose_name='خطأ الإرسال'),
        ),
        migrations.AddField(
            model_name='employeestatement',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الإيميل'),
        ),
        migrations.AddField(
            model_name='employeestatement',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الموظف للإرسال'),
        ),
        migrations.AddField(
            model_name='employeestatement',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='employeestatement',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: STM-2026-0001', max_length=30, verbose_name='الرقم المتسلسل'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='email_error',
            field=models.TextField(blank=True, verbose_name='خطأ الإرسال'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الإيميل'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الموظف للإرسال'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: STM-2026-0001', max_length=30, verbose_name='الرقم المتسلسل'),
        ),
        migrations.AlterField(
            model_name='employeestatement',
            name='statement_type',
            field=models.CharField(choices=[('statement', 'إفادة'), ('warning', 'إنذار'), ('final_warning', 'إنذار نهائي'), ('acknowledgment', 'إقرار'), ('terminate', 'تصفية'), ('reactivate', 'إعادة تفعيل'), ('salary_adjust', 'تعديل راتب'), ('transfer', 'نقل'), ('other', 'أخرى')], default='statement', max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='historicalemployeestatement',
            name='statement_type',
            field=models.CharField(choices=[('statement', 'إفادة'), ('warning', 'إنذار'), ('final_warning', 'إنذار نهائي'), ('acknowledgment', 'إقرار'), ('terminate', 'تصفية'), ('reactivate', 'إعادة تفعيل'), ('salary_adjust', 'تعديل راتب'), ('transfer', 'نقل'), ('other', 'أخرى')], default='statement', max_length=20, verbose_name='النوع'),
        ),
    ]
