# Generated by Django 5.2.12 on 2026-04-28 12:43

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeestatement_email_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commencement_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/commencement/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/contract/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='employees/other/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستندات أخرى'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/passport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='جواز السفر'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/leaves/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employeestatement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/statements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='commencement_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='commencement_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='contract_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='id_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='other_documents',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستندات أخرى'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='passport_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='جواز السفر'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeleave',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemployeestatement',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='commencement_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند المباشرة'),
        ),
    ]
