# Generated by Django 5.2.12 on 2026-04-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_commencement_document_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='employee',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.insurance', verbose_name='التأمين الطبي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.insuranceclass', verbose_name='فئة التأمين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.nationality', verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.profession', verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.sponsorship', verbose_name='الكفالة'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='insurance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.insurance', verbose_name='التأمين الطبي'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='insurance_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.insuranceclass', verbose_name='فئة التأمين'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='nationality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.nationality', verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='profession',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.profession', verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='sponsorship',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.sponsorship', verbose_name='الكفالة'),
        ),
            ],
            database_operations=[],
        ),
    ]
