# Generated by Django 5.2.12 on 2026-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز'),
        ),
    ]
