# Generated by Django 5.2.12 on 2026-05-02 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_passport_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإسناد'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employment_requests', to=settings.AUTH_USER_MODEL, verbose_name='أخصائي الموارد المُسند'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='branch_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مدير الفرع'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='branch_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة مدير الفرع'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='branch_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_reviewed_employment_requests', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع المراجِع'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='gm_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مدير الموارد'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='gm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة مدير الموارد'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='gm_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_reviewed_employment_requests', to=settings.AUTH_USER_MODEL, verbose_name='مدير الموارد المراجِع'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='officer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الأخصائي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة الأخصائي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإسناد'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أخصائي الموارد المُسند'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='branch_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مدير الفرع'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='branch_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة مدير الفرع'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='branch_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع المراجِع'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='gm_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مدير الموارد'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='gm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة مدير الموارد'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='gm_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مدير الموارد المراجِع'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='officer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الأخصائي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة الأخصائي'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('pending_branch', 'بانتظار مدير الفرع'), ('pending_gm', 'بانتظار مدير الموارد'), ('pending_officer', 'بانتظار أخصائي الموارد'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending_branch', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('pending_branch', 'بانتظار مدير الفرع'), ('pending_gm', 'بانتظار مدير الموارد'), ('pending_officer', 'بانتظار أخصائي الموارد'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending_branch', max_length=20, verbose_name='الحالة'),
        ),
    ]
