# Generated by Django 5.2.12 on 2026-05-03 16:11

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_migrate_employment_request_statuses'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrequest',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='كاش'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/contract/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المباشرة'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل سكن'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='صورة الهوية'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.insurance', verbose_name='التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='insurance_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.insuranceclass', verbose_name='فئة التأمين'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='insurance_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم التأمينات'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.nationality', verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل إضافي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/other/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستندات أخرى'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/passport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='جواز السفر'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.profession', verbose_name='المهنة'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.sponsorship', verbose_name='الكفالة'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل نقل'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='كاش'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='contract_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المباشرة'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل سكن'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='id_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='صورة الهوية'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='insurance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.insurance', verbose_name='التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='insurance_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.insuranceclass', verbose_name='فئة التأمين'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='insurance_deduction_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم التأمينات'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='nationality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.nationality', verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل إضافي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='other_documents',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستندات أخرى'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='passport_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='جواز السفر'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='profession',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.profession', verbose_name='المهنة'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='sponsorship',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.sponsorship', verbose_name='الكفالة'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل نقل'),
        ),
    ]
