# Generated by Django 5.2.12 on 2026-05-09 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employmentrequest_basic_salary_and_more'),
        ('setup', '0002_building_historicalbuilding'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='health_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='not_available', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.building', verbose_name='السكن'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='health_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='not_available', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='housing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.building', verbose_name='السكن'),
        ),
    ]
