# Generated by Django 5.2.12 on 2026-05-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_health_card_expiry_and_more'),
        ('setup', '0003_bank_historicalbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='setup.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='رقم الآيبان'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='رقم الآيبان'),
        ),
    ]
