# Generated by Django 5.2.12 on 2026-05-12 14:34

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employeebusinesstrip_employeecustody_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='مثال: LN-260512-0005-A3F2', max_length=40, verbose_name='الرقم المتسلسل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ السلفة')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الخصم الشهري')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب السلفة')),
                ('issued_at', models.DateField(verbose_name='تاريخ الصرف')),
                ('first_deduction_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('document', models.FileField(blank=True, null=True, upload_to='employees/loans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق')),
                ('status', models.CharField(choices=[('active', 'قيد السداد'), ('paid', 'مُسدَّدة'), ('cancelled', 'مُلغاة')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='أُضيفت بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة موظف',
                'verbose_name_plural': 'سلف الموظفين',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeLoan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='مثال: LN-260512-0005-A3F2', max_length=40, verbose_name='الرقم المتسلسل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ السلفة')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الخصم الشهري')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب السلفة')),
                ('issued_at', models.DateField(verbose_name='تاريخ الصرف')),
                ('first_deduction_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('document', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق')),
                ('status', models.CharField(choices=[('active', 'قيد السداد'), ('paid', 'مُسدَّدة'), ('cancelled', 'مُلغاة')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أُضيفت بواسطة')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='الموظف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical سلفة موظف',
                'verbose_name_plural': 'historical سلف الموظفين',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
