# Generated by Django 5.2.12 on 2026-05-12 16:00

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employeeloan_historicalemployeeloan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='مثال: AB-260512-0005-A3F2', max_length=40, verbose_name='الرقم المتسلسل')),
                ('absence_date', models.DateField(db_index=True, verbose_name='تاريخ الغياب')),
                ('days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد أيام الغياب')),
                ('month_days', models.PositiveIntegerField(default=30, help_text='عدد أيام الشهر الذي وقع فيه الغياب (28/29/30/31) — لقطة عند الإنشاء', verbose_name='أيام الشهر')),
                ('total_salary_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الراتب وقت الغياب')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي الراتب ÷ أيام الشهر', max_digits=12, verbose_name='سعر اليوم (محسوب)')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, help_text='سعر اليوم × عدد أيام الغياب', max_digits=12, verbose_name='إجمالي الخصم')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب الغياب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('document', models.FileField(blank=True, null=True, upload_to='employees/absences/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_absences', to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'غياب موظف',
                'verbose_name_plural': 'غيابات الموظفين',
                'ordering': ['-absence_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeAbsence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='مثال: AB-260512-0005-A3F2', max_length=40, verbose_name='الرقم المتسلسل')),
                ('absence_date', models.DateField(db_index=True, verbose_name='تاريخ الغياب')),
                ('days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد أيام الغياب')),
                ('month_days', models.PositiveIntegerField(default=30, help_text='عدد أيام الشهر الذي وقع فيه الغياب (28/29/30/31) — لقطة عند الإنشاء', verbose_name='أيام الشهر')),
                ('total_salary_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الراتب وقت الغياب')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي الراتب ÷ أيام الشهر', max_digits=12, verbose_name='سعر اليوم (محسوب)')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, help_text='سعر اليوم × عدد أيام الغياب', max_digits=12, verbose_name='إجمالي الخصم')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب الغياب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('document', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size], verbose_name='مستند مرفق')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='الموظف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical غياب موظف',
                'verbose_name_plural': 'historical غيابات الموظفين',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
