# Generated by Django 5.2.12 on 2026-05-12 17:01

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employeeabsence_historicalemployeeabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoanInstallment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('period_year', models.PositiveIntegerField(db_index=True, verbose_name='السنة')),
                ('period_month', models.PositiveSmallIntegerField(db_index=True, verbose_name='الشهر')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'مستحق'), ('paid', 'مُحصَّل'), ('skipped', 'مؤجَّل'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical قسط سلفة',
                'verbose_name_plural': 'historical أقساط السلف',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('period_year', models.PositiveIntegerField(db_index=True, verbose_name='السنة')),
                ('period_month', models.PositiveSmallIntegerField(db_index=True, verbose_name='الشهر')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'مستحق'), ('paid', 'مُحصَّل'), ('skipped', 'مؤجَّل'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'قسط سلفة',
                'verbose_name_plural': 'أقساط السلف',
                'ordering': ['period_year', 'period_month'],
            },
        ),
    ]
