# Generated by Django 5.2.12 on 2026-05-12 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_historicalloaninstallment_loaninstallment'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_absences', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_unpaid_leaves', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه (للإجازات بدون راتب)'),
        ),
        migrations.AddField(
            model_name='employeestatement',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_penalties', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه'),
        ),
        migrations.AddField(
            model_name='employeestatement',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="يُطبَّق فقط عند النوع 'مخالفة' ويظهر تلقائياً في المسير الشهري", max_digits=12, verbose_name='مبلغ الخصم'),
        ),
        migrations.AddField(
            model_name='historicalemployeeabsence',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه'),
        ),
        migrations.AddField(
            model_name='historicalemployeeleave',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه (للإجازات بدون راتب)'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه'),
        ),
        migrations.AddField(
            model_name='historicalemployeestatement',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="يُطبَّق فقط عند النوع 'مخالفة' ويظهر تلقائياً في المسير الشهري", max_digits=12, verbose_name='مبلغ الخصم'),
        ),
        migrations.AlterField(
            model_name='employeestatement',
            name='statement_type',
            field=models.CharField(choices=[('statement', 'إفادة'), ('warning', 'إنذار'), ('final_warning', 'إنذار نهائي'), ('penalty', 'مخالفة (خصم مالي)'), ('acknowledgment', 'إقرار'), ('terminate', 'تصفية'), ('reactivate', 'إعادة تفعيل'), ('salary_adjust', 'تعديل راتب'), ('transfer', 'نقل'), ('other', 'أخرى')], default='statement', max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='historicalemployeestatement',
            name='statement_type',
            field=models.CharField(choices=[('statement', 'إفادة'), ('warning', 'إنذار'), ('final_warning', 'إنذار نهائي'), ('penalty', 'مخالفة (خصم مالي)'), ('acknowledgment', 'إقرار'), ('terminate', 'تصفية'), ('reactivate', 'إعادة تفعيل'), ('salary_adjust', 'تعديل راتب'), ('transfer', 'نقل'), ('other', 'أخرى')], default='statement', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='historicalloaninstallment',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه'),
        ),
        migrations.AddField(
            model_name='historicalloaninstallment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloaninstallment',
            name='loan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employeeloan', verbose_name='السلفة'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='applied_to_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_loan_installments', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments_log', to='employees.employeeloan', verbose_name='السلفة'),
        ),
        migrations.AlterUniqueTogether(
            name='loaninstallment',
            unique_together={('loan', 'period_year', 'period_month')},
        ),
    ]
