# Generated by Django 5.2.12 on 2026-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employeeabsence_applied_to_payroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='available_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='عدد أيام الإجازات السنوية المأخوذة فعلياً — يزداد مع كل إجازة معتمدة. الرصيد المتبقي = المستحق − هذا الحقل.', max_digits=8, verbose_name='أيام الإجازة المستخدمة'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='available_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='عدد أيام الإجازات السنوية المأخوذة فعلياً — يزداد مع كل إجازة معتمدة. الرصيد المتبقي = المستحق − هذا الحقل.', max_digits=8, verbose_name='أيام الإجازة المستخدمة'),
        ),
    ]
