# Generated by Django 5.2.12 on 2026-05-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_fix_ledger_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية العقد المخطط — منفصل عن «تاريخ التوقف» عند التصفية الفعلية.', null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_insurance_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ تجديد بوليصة التأمين الصحي للموظف (وليس جدول نوع التأمين في الإعدادات).', null=True, verbose_name='تاريخ انتهاء التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء بطاقة الإقامة/الخروج والعودة إن وُجد.', null=True, verbose_name='تاريخ انتهاء الإقامة'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='contract_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية العقد المخطط — منفصل عن «تاريخ التوقف» عند التصفية الفعلية.', null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='medical_insurance_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ تجديد بوليصة التأمين الصحي للموظف (وليس جدول نوع التأمين في الإعدادات).', null=True, verbose_name='تاريخ انتهاء التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='residency_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء بطاقة الإقامة/الخروج والعودة إن وُجد.', null=True, verbose_name='تاريخ انتهاء الإقامة'),
        ),
    ]
