# Generated by Django 5.2.12 on 2026-05-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_employee_compliance_expiry_dates'),
        ('setup', '0003_bank_historicalbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrequest',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='contract_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية العقد المخطط.', null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='health_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='not_available', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_requests', to='setup.building', verbose_name='السكن'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='رقم الآيبان'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='medical_insurance_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ تجديد بوليصة التأمين الصحي للموظف.', null=True, verbose_name='تاريخ انتهاء التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='residency_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء بطاقة الإقامة/الخروج والعودة إن وُجد.', null=True, verbose_name='تاريخ انتهاء الإقامة'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='contract_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية العقد المخطط.', null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='health_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='not_available', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='housing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setup.building', verbose_name='السكن'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='رقم الآيبان'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='medical_insurance_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ تجديد بوليصة التأمين الصحي للموظف.', null=True, verbose_name='تاريخ انتهاء التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='residency_expiry_date',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء بطاقة الإقامة/الخروج والعودة إن وُجد.', null=True, verbose_name='تاريخ انتهاء الإقامة'),
        ),
    ]
