# Generated by Django 5.2.12 on 2026-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_employmentrequest_full_employee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeledger',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث'),
        ),
    ]
