# Generated by Django 5.2.12 on 2026-06-04 02:22

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='emp_branch_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='emp_branch_del_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeabsence',
            name='empabs_emp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='employmentrequest',
            name='er_status_branch_idx',
        ),
        migrations.AlterField(
            model_name='employee',
            name='commencement_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/commencement/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/contract/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='employees/other/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستندات أخرى'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/passport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='جواز السفر'),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/absences/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employeebusinesstrip',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/business_trips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employeecustody',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/custody/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند الاستلام'),
        ),
        migrations.AlterField(
            model_name='employeecustody',
            name='return_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/custody/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند التصفية'),
        ),
        migrations.AlterField(
            model_name='employeejoboffer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/job_offers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/leaves/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/loans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employeestatement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/statements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='commencement_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/contract/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/other/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستندات أخرى'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='employment_requests/passport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='جواز السفر'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='commencement_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='contract_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='id_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='other_documents',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستندات أخرى'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='passport_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='جواز السفر'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeabsence',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemployeebusinesstrip',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemployeecustody',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند الاستلام'),
        ),
        migrations.AlterField(
            model_name='historicalemployeecustody',
            name='return_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند التصفية'),
        ),
        migrations.AlterField(
            model_name='historicalemployeejoboffer',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeleave',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeloan',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemployeestatement',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='commencement_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند المباشرة'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='contract_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='id_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='other_documents',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستندات أخرى'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='passport_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='جواز السفر'),
        ),
    ]
