# Generated by Django 5.2.12 on 2026-06-09 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_core_pendin_adminis_d3e0f8_idx_core_pendin_adminis_27f153_idx_and_more'),
        ('cost_centers', '0002_alter_costcenter_branch'),
        ('departments', '0002_alter_department_branch'),
        ('employees', '0034_employee_account_type'),
        ('payroll', '0006_payroll_run_kind_history'),
        ('setup', '0006_administration_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='month_days',
            field=models.PositiveIntegerField(default=30, help_text='أيام الشهر للحساب (ثابت 30) — لقطة عند الإنشاء', verbose_name='أيام الشهر'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeabsence',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='إجمالي الراتب ÷ 30', max_digits=12, verbose_name='سعر اليوم (محسوب)'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeabsence',
            name='month_days',
            field=models.PositiveIntegerField(default=30, help_text='أيام الشهر للحساب (ثابت 30) — لقطة عند الإنشاء', verbose_name='أيام الشهر'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch', 'status'], name='emp_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch', 'is_deleted'], name='emp_branch_del_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeabsence',
            index=models.Index(fields=['employee', 'absence_date'], name='empabs_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentrequest',
            index=models.Index(fields=['status', 'branch'], name='er_status_branch_idx'),
        ),
    ]
