# Generated by Django 5.2.12 on 2026-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_restore_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentrequest',
            name='health_card_status',
            field=models.CharField(blank=True, choices=[('available', 'متوفر'), ('not_available', 'غير متوفر')], default='', max_length=20, verbose_name='حالة الكرت الصحي'),
        ),
    ]
