# Generated by Django 5.2.12 on 2026-06-19 23:57

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cash_shortage_feature'),
        ('employees', '0036_blank_defaults_gender_health_card'),
        ('payroll', '0009_cash_shortage_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployeeCashShortage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='مثال: CS-260620-0005-A3F2', max_length=40, verbose_name='الرقم المتسلسل')),
                ('shortage_date', models.DateField(db_index=True, verbose_name='تاريخ العجز')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ العجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applied_to_payroll', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='الموظف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical عجز كاشير',
                'verbose_name_plural': 'historical عجوزات الكاشير',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeeCashShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='مثال: CS-260620-0005-A3F2', max_length=40, verbose_name='الرقم المتسلسل')),
                ('shortage_date', models.DateField(db_index=True, verbose_name='تاريخ العجز')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ العجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('applied_to_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_cash_shortages', to='payroll.payrollrun', verbose_name='المسير المُحتسب فيه')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shortages', to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_shortages', to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shortages', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عجز كاشير',
                'verbose_name_plural': 'عجوزات الكاشير',
                'ordering': ['-shortage_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'shortage_date'], name='empcs_emp_date_idx')],
            },
        ),
    ]
