# Generated by Django 5.2.12 on 2026-06-20 00:16

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_cash_shortage_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecashshortage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/cash_shortages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
        migrations.AddField(
            model_name='historicalemployeecashshortage',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: pdf, jpg, jpeg, png, webp, doc, docx'), apps.core.validators.validate_file_size, apps.core.validators.validate_upload_magic_bytes], verbose_name='مستند مرفق'),
        ),
    ]
