# Generated by Django 5.2.12 on 2026-05-09 09:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم العمارة')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العمارة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('rent_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإيجار')),
                ('water_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الماء')),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الكهرباء')),
                ('cleaning_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة النظافة')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة النقل')),
                ('furniture_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة المفروشات')),
                ('tools_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الأدوات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عمارة',
                'verbose_name_plural': 'العمارات',
                'db_table': 'setup_building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBuilding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='رقم العمارة')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العمارة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('rent_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإيجار')),
                ('water_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الماء')),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الكهرباء')),
                ('cleaning_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة النظافة')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة النقل')),
                ('furniture_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة المفروشات')),
                ('tools_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الأدوات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical عمارة',
                'verbose_name_plural': 'historical العمارات',
                'db_table': 'setup_historicalbuilding',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
