# Generated by Django 5.2.12 on 2026-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_administration_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsponsorship',
            name='commercial_registration',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='commercial_registration',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='السجل التجاري'),
        ),
    ]
