# Generated by Django 5.2.12 on 2026-06-17 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_administration_report_recipient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsreportsettings',
            name='send_time',
            field=models.TimeField(default=datetime.time(12, 0), help_text='يُرسل يومياً عند هذا الوقت (توقيت Django — TIME_ZONE).', verbose_name='وقت الإرسال'),
        ),
    ]
