# Generated by Django 5.2.12 on 2026-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_evolution_whatsapp_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowWhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='يرسل تنبيهات عند رفع الطلبات ومراحل الموافقة.', verbose_name='تفعيل إشعارات واتساب لسير العمل')),
                ('recipient_phones', models.JSONField(blank=True, default=dict, help_text='مفاتيح: system_admin, hr_manager', verbose_name='جوال واتساب حسب الدور')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات واتساب — سير العمل',
                'verbose_name_plural': 'إعدادات واتساب — سير العمل',
                'db_table': 'setup_workflowwhatsappsettings',
            },
        ),
    ]
